version: '3.4'

services:
  db:
    image: mysql:5.7
    volumes:
    - dbdata:/var/lib/mysql
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    build:
      context: ./
      dockerfile: Dockerfile-wordpress
    depends_on:
    - db
    volumes:
      - ./root:/var/www/html
      - ./wp-content:/var/www/html/wp-content/
    ports:
    - "8888:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      XDEBUG_CONFIG: remote_host=host.docker.internal

  phpmyadmin:
    depends_on:
    - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
    - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
volumes:
  dbdata:
