version: '3'

services:
  db:
    container_name: "wp-db"
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MY_SQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MY_SQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  wordpress:
    container_name: "wp-core"
    build:
      context: ./
      dockerfile: Dockerfile-wordpress
    depends_on:
      - db
    volumes:
      - ./root:/var/www/html/
      - ./wp-content:/var/www/html/wp-content/
    ports:
      - ${WORDPRESS_PORT}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:${MYSQL_PORT}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DEBUG: 1
      XDEBUG_CONFIG: remote_host=host.docker.internal

  wp-cli:
    container_name: 'wp-cli'
    depends_on:
      - wordpress
      - db
    image: conetix/wordpress-with-wp-cli
    command: >
      'wp core install --path="/var/www/html" --url="http://localhost:${WORDPRESS_PORT}" --title="${WORDPRESS_SITE_NAME}" --admin_user=${WORDPRESS_ADMIN} --admin_password=${WORDPRESS_ADMIN_PASSWORD} --admin_email=${WORDPRESS_ADMIN_EMAIL};
       wp theme activate 'boilerplate-theme';
      '
    volumes:
      - ./root:/var/www/html/
      - ./wp-content:/var/www/html/wp-content/

  phpmyadmin:
    container_name: "wp-phpmyadmin"
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
volumes:
  dbdata:
